### ISSUE TITLE
"Sean Connery" Bug

### ISSUE THREAD

**Issue by RyPoints** [Djarnis/xgoogle#1]
This functions for some queries, but certain queries that should return results do not.

Do a search for "nice" a search for "sean connery" or a search for "infinite" and you will always see None for the results.

A search for "great" causes a crash if you attempt to read the description.

**Comment by RyPoints** [comment]
I've forked your code and mended this here:

https://github.com/RyPoints/xgoogle

**Comment by Djarnis** [comment]
Cool, Ryan :)
